<?php $v->layout('template', ['title' => 'Slack Stats - User Detail']) ?>
<?php include('form.phtml'); ?>
<div class="chart-container" style="margin-top: 30px; position: relative; height:40vh;">
    <canvas id="myChart"></canvas>
</div>
<script>
    $(document).ready(function() {
        var chartColors = {
            color1: 'rgb(109,181,127, 0.5)',
            color2: 'rgba(192,35,89, 0.5)',
        };
        const ctx = document.getElementById('myChart').getContext('2d');
        const data = {
            // Labels should be Date objects
            labels: [
                <?php
                $i = 0;
                $len = count($data);
                foreach ($data as $d) { ?>
                    new moment('<?= $d['time'] ?>') <?php if ($i < $len - 1) { ?>, <?php } ?>
                    <?php
                    $i++;
                }
                ?>
            ],
            datasets: [{
                fill: false,
                label: 'Slack Status',
                data: [<?php
                        $i = 0;
                        $len = count($data);
                        foreach ($data as $d) { ?><?php if ($d['presence'] == 'active') { ?>1<?php } else { ?> .2 <?php }
                                                                                        if ($i < $len - 1) { ?>, <?php } ?><?php
                                                                                                                                        $i++;
                                                                                                                                    }
                                                                                                                                    ?>],
                backgroundColor: [<?php
                                    $i = 0;
                                    $len = count($data);
                                    foreach ($data as $d) { ?><?php if ($d['presence'] == 'active') { ?>chartColors.color1<?php } else { ?>chartColors.color2<?php }
                                                                                                                        if ($i < $len - 1) { ?>, <?php } ?><?php
                                                                                                                                                                    $i++;
                                                                                                                                                                }
                                                                                                                                                                ?>],
                borderColor: '#eee'
            }]
        }
        const options = {
            type: 'bar',
            data: data,
            options: {
                fill: false,
                responsive: true,
                maintainAspectRatio: false,
                legend: {
                    display: false
                },
                tooltips: {
                    callbacks: {
                        label: function(tooltipItem, data) {
                            var label = data.datasets[tooltipItem.datasetIndex].label || '';
                            label += ': ';
                            if (tooltipItem.yLabel < 1) {
                                label += "Online";
                            } else {
                                label += "Online";
                            }
                            return label;
                        }
                    }
                },
                scales: {
                    xAxes: [{
                        type: 'time',
                        time: {
                            unit: 'hour',
                            displayFormats: {
                                day: 'MMM D',
                                hour: 'hA'
                            },
                            //dynamically adjust according to the number of days in the chart to avoid crowding
                            stepSize: <?php if ($days >= 4) { ?>12<?php } else {
                                                                echo 3;
                                                            } ?>
                        },
                        overrideRotation: 45,
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: "Date & Time",
                        },
                        ticks: {
                            source: 'auto',
                            autoSkip: true,
                            major: {
                                enabled: true,
                                fontStyle: '500',
                                callback: function(value, index, values) {
                                    return value;
                                }
                            },
                            minor: {
                                fontStyle: '300',
                                callback: function(value, index, values) {
                                    return value;
                                }
                            }
                        },
                        categoryPercentage: 1,
                        barPercentage: 1,
                        barThickness: 'flex'
                    }],
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            max: 1,
                            callback: function(value, index, values) {
                                if (value === 1) {
                                    return 'Online';
                                }
                                if (value == 0) {
                                    return 'Offline';
                                }
                            }
                        },
                        display: true,
                        scaleLabel: {
                            display: false,
                            labelString: "Status",
                        }
                    }]
                }
            }
        }
        const chart = new Chart(ctx, options);
        chart.canvas.parentNode.style.height = '50vh';
    });
</script>
